import { Food } from './types';

export interface NhomThucDon {
  ma: 'tat_ca' | 'mon_viet' | 'gym_healthy' | 'tinh_bot' | 'thit_dam' | 'mon_nuoc' | 'rau_qua' | 'do_uong' | 'khac';
  ten: string;
}

export const NHOM_THUC_DON: NhomThucDon[] = [
  { ma: 'tat_ca', ten: 'Tất cả' },
  { ma: 'mon_viet', ten: 'Món Việt' },
  { ma: 'gym_healthy', ten: 'Gym & Healthy' },
  { ma: 'tinh_bot', ten: 'Tinh bột' },
  { ma: 'thit_dam', ten: 'Thịt & Đạm' },
  { ma: 'mon_nuoc', ten: 'Món nước' },
  { ma: 'rau_qua', ten: 'Rau & Quả' },
  { ma: 'do_uong', ten: 'Đồ uống' },
];

export const THUC_DON_MAC_DINH: Food[] = [
  // ==========================================
  // PHẦN 1: MÓN ĂN CHÍNH VIỆT NAM THƯỜNG NGÀY (~62 món)
  // ==========================================
  {
    id: 1,
    ten: 'Phở bò tái',
    kcal: 430,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 25.0,
    bot: 58.0,
    beo: 10.5,
    moTa: 'Tô phở bò tái truyền thống ~500g',
  },
  {
    id: 2,
    ten: 'Phở bò nạm gầu',
    kcal: 520,
    gram: 550,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 28.0,
    bot: 60.0,
    beo: 18.0,
    moTa: 'Tô phở nạm gầu đậm đà ~550g',
  },
  {
    id: 3,
    ten: 'Phở gà ta',
    kcal: 410,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 26.0,
    bot: 56.0,
    beo: 9.0,
    moTa: 'Phở thịt gà ta xé lá chanh',
  },
  {
    id: 4,
    ten: 'Bún bò Huế',
    kcal: 550,
    gram: 550,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 30.0,
    bot: 62.0,
    beo: 19.0,
    moTa: 'Bún bò Huế bắp bò chả cua huyết giò',
  },
  {
    id: 5,
    ten: 'Bún chả nướng Hà Nội',
    kcal: 580,
    gram: 400,
    donVi: 'suất',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 28.0,
    bot: 65.0,
    beo: 22.0,
    moTa: '1 suất bún sợi, chả băm & chả miếng nướng than',
  },
  {
    id: 6,
    ten: 'Bún riêu cua đồng',
    kcal: 420,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 20.0,
    bot: 58.0,
    beo: 12.0,
    moTa: 'Bún riêu cua đậu phụ cà chua huyết',
  },
  {
    id: 7,
    ten: 'Bún ốc chuối đậu',
    kcal: 440,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 22.0,
    bot: 60.0,
    beo: 12.0,
    moTa: 'Bún ốc nóng tía tô chuối đậu',
  },
  {
    id: 8,
    ten: 'Bún đậu mắm tôm thập cẩm',
    kcal: 620,
    gram: 450,
    donVi: 'mẹt',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 29.0,
    bot: 60.0,
    beo: 28.0,
    moTa: 'Bún lá, đậu chiên giòn, thịt luộc, chả cốm',
  },
  {
    id: 9,
    ten: 'Bún thịt nướng chả giò',
    kcal: 570,
    gram: 450,
    donVi: 'tô',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 24.0,
    bot: 68.0,
    beo: 22.0,
    moTa: 'Bún thịt nướng mè, chả giò, rau sống, mỡ hành',
  },
  {
    id: 10,
    ten: 'Bún mắm miền Tây',
    kcal: 510,
    gram: 550,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 30.0,
    bot: 62.0,
    beo: 15.0,
    moTa: 'Bún mắm tôm, mực, heo quay, cà tím',
  },
  {
    id: 11,
    ten: 'Bún mọc sườn non',
    kcal: 460,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 24.0,
    bot: 58.0,
    beo: 14.0,
    moTa: 'Bún mọc giò sống nấm hương, sườn mềm',
  },
  {
    id: 12,
    ten: 'Bún cá rô đồng cay',
    kcal: 430,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 25.0,
    bot: 60.0,
    beo: 10.0,
    moTa: 'Bún cá rô rán giòn, dọc mùng thì là',
  },
  {
    id: 13,
    ten: 'Hủ tiếu Nam Vang nước',
    kcal: 480,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 26.0,
    bot: 62.0,
    beo: 14.0,
    moTa: 'Hủ tiếu tôm tươi, gan heo, thịt bằm, trứng cút',
  },
  {
    id: 14,
    ten: 'Hủ tiếu Nam Vang khô',
    kcal: 530,
    gram: 450,
    donVi: 'tô',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 27.0,
    bot: 65.0,
    beo: 17.0,
    moTa: 'Hủ tiếu trộn sốt đậm đà kèm chén súp',
  },
  {
    id: 15,
    ten: 'Hủ tiếu sườn heo',
    kcal: 490,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 28.0,
    bot: 60.0,
    beo: 15.0,
    moTa: 'Hủ tiếu nước dùng hầm sườn heo thanh ngọt',
  },
  {
    id: 16,
    ten: 'Bánh canh cua giò heo',
    kcal: 530,
    gram: 550,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 28.0,
    bot: 64.0,
    beo: 17.0,
    moTa: 'Sợi bánh canh dai, thịt cua, giò heo, nấm rơm',
  },
  {
    id: 17,
    ten: 'Bánh canh chả cá Nha Trang',
    kcal: 410,
    gram: 500,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 22.0,
    bot: 60.0,
    beo: 9.0,
    moTa: 'Bánh canh chả cá thu hấp chiên, cá dầm',
  },
  {
    id: 18,
    ten: 'Mì Quảng tôm thịt trứng',
    kcal: 490,
    gram: 450,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 24.0,
    bot: 60.0,
    beo: 16.0,
    moTa: 'Mì Quảng sợi vàng, tôm thịt kho rim, bánh tráng',
  },
  {
    id: 19,
    ten: 'Cao lầu Hội An',
    kcal: 460,
    gram: 400,
    donVi: 'tô',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 22.0,
    bot: 58.0,
    beo: 15.0,
    moTa: 'Sợi cao lầu, thịt xá xíu, tóp mỡ giòn rụm',
  },
  {
    id: 20,
    ten: 'Miến gà ta hành hoa',
    kcal: 390,
    gram: 450,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 24.0,
    bot: 54.0,
    beo: 8.0,
    moTa: 'Miến dong nấu nước luộc gà, thịt gà xé',
  },
  {
    id: 21,
    ten: 'Miến lươn xào giòn',
    kcal: 450,
    gram: 350,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 25.0,
    bot: 56.0,
    beo: 14.0,
    moTa: 'Miến xào lươn giòn, mộc nhĩ, rau răm',
  },
  {
    id: 22,
    ten: 'Cơm tấm sườn nướng',
    kcal: 520,
    gram: 350,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 26.0,
    bot: 68.0,
    beo: 16.0,
    moTa: 'Cơm tấm 1 miếng sườn cốt lết nướng mỡ hành',
  },
  {
    id: 23,
    ten: 'Cơm tấm sườn bì chả trứng',
    kcal: 720,
    gram: 450,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 36.0,
    bot: 75.0,
    beo: 29.0,
    moTa: '1 đĩa cơm tấm đầy đủ sườn bì chả trứng ốp la',
  },
  {
    id: 24,
    ten: 'Cơm rang dưa bò',
    kcal: 560,
    gram: 350,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 25.0,
    bot: 70.0,
    beo: 20.0,
    moTa: 'Cơm rang vàng giòn, thịt bò xào dưa chua',
  },
  {
    id: 25,
    ten: 'Cơm rang thập cẩm',
    kcal: 540,
    gram: 350,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 20.0,
    bot: 72.0,
    beo: 18.0,
    moTa: 'Cơm rang lạp xưởng, trứng, cà rốt, đậu cô ve',
  },
  {
    id: 26,
    ten: 'Cơm gà xối mỡ đùi góc tư',
    kcal: 680,
    gram: 400,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 32.0,
    bot: 70.0,
    beo: 28.0,
    moTa: 'Cơm chiên cà chua kèm đùi gà xối mỡ da giòn',
  },
  {
    id: 27,
    ten: 'Cơm gà luộc Hội An',
    kcal: 480,
    gram: 350,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 30.0,
    bot: 65.0,
    beo: 11.0,
    moTa: 'Cơm nấu nước luộc gà nghệ, gà xé bóp gỏi',
  },
  {
    id: 28,
    ten: 'Bánh mì kẹp thịt chả pate',
    kcal: 430,
    gram: 150,
    donVi: 'ổ',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 16.0,
    bot: 50.0,
    beo: 18.0,
    moTa: 'Bánh mì giòn pate, thịt nguội, giò chả, đồ chua',
  },
  {
    id: 29,
    ten: 'Bánh mì ốp la xúc xích',
    kcal: 410,
    gram: 160,
    donVi: 'ổ',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 15.0,
    bot: 48.0,
    beo: 17.0,
    moTa: 'Bánh mì kẹp 1 trứng ốp la + 1 cây xúc xích',
  },
  {
    id: 30,
    ten: 'Bánh mì chảo xíu mại trứng',
    kcal: 510,
    gram: 250,
    donVi: 'phần',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 22.0,
    bot: 52.0,
    beo: 24.0,
    moTa: 'Chảo pate, xíu mại, 2 trứng ốp, 1 ổ bánh mì',
  },
  {
    id: 31,
    ten: 'Bánh cuốn nóng chả lụa',
    kcal: 390,
    gram: 300,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 14.0,
    bot: 60.0,
    beo: 10.0,
    moTa: 'Bánh cuốn thịt mộc nhĩ kèm 2 lát chả lụa',
  },
  {
    id: 32,
    ten: 'Bánh xèo miền Tây',
    kcal: 450,
    gram: 250,
    donVi: 'cái',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 16.0,
    bot: 48.0,
    beo: 21.0,
    moTa: 'Vỏ bánh giòn nhân tôm thịt giá đỗ cuốn cải xanh',
  },
  {
    id: 33,
    ten: 'Bánh khọt tôm thịt',
    kcal: 380,
    gram: 200,
    donVi: 'đĩa',
    nhom: 'tinh_bot',
    phanLoai: 'mon_viet',
    dam: 14.0,
    bot: 42.0,
    beo: 17.0,
    moTa: 'Đĩa 5 chiếc bánh khọt Vũng Tàu nhân tôm',
  },
  {
    id: 34,
    ten: 'Nem rán / Chả giò chiên',
    kcal: 330,
    gram: 120,
    donVi: 'phần',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 12.0,
    bot: 25.0,
    beo: 20.0,
    moTa: '3 cuốn chả giò thịt mộc nhĩ miến chiên giòn',
  },
  {
    id: 35,
    ten: 'Gỏi cuốn tôm thịt',
    kcal: 210,
    gram: 180,
    donVi: 'phần',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 14.0,
    bot: 28.0,
    beo: 4.5,
    moTa: '3 cuốn tôm thịt luộc bún rau thơm chấm tương',
  },
  {
    id: 36,
    ten: 'Thịt kho tàu trứng vịt',
    kcal: 380,
    gram: 150,
    donVi: 'chén',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 20.0,
    bot: 8.0,
    beo: 30.0,
    moTa: 'Thịt ba rọi kho nước dừa + 1 trứng vịt',
  },
  {
    id: 37,
    ten: 'Sườn heo ram mặn ngọt',
    kcal: 340,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 24.0,
    bot: 12.0,
    beo: 21.0,
    moTa: 'Sườn non chặt khúc kho ram mặn ngọt óng ánh',
  },
  {
    id: 38,
    ten: 'Sườn xào chua ngọt',
    kcal: 360,
    gram: 180,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 22.0,
    bot: 20.0,
    beo: 20.0,
    moTa: 'Sườn non xào sốt cà chua, giấm đường thơm nức',
  },
  {
    id: 39,
    ten: 'Thịt ba chỉ rang cháy cạnh',
    kcal: 350,
    gram: 120,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 18.0,
    bot: 5.0,
    beo: 29.0,
    moTa: 'Thịt ba chỉ thái mỏng rang sém vàng tỏi ớt',
  },
  {
    id: 40,
    ten: 'Thịt luộc chấm mắm tôm cà',
    kcal: 320,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 24.0,
    bot: 3.0,
    beo: 24.0,
    moTa: 'Thịt chân giò/ba chỉ luộc thái mỏng',
  },
  {
    id: 41,
    ten: 'Bò xào cần tỏi tây',
    kcal: 260,
    gram: 200,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 26.0,
    bot: 6.0,
    beo: 14.0,
    moTa: 'Thịt bò thăn xào lửa lớn với cần tây, tỏi tây',
  },
  {
    id: 42,
    ten: 'Bò lúc lắc khoai tây',
    kcal: 430,
    gram: 250,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 28.0,
    bot: 32.0,
    beo: 21.0,
    moTa: 'Bò lúc lắc áp chảo bơ tỏi ăn kèm khoai tây',
  },
  {
    id: 43,
    ten: 'Bò sốt vang bánh mì',
    kcal: 380,
    gram: 250,
    donVi: 'bát',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 26.0,
    bot: 18.0,
    beo: 21.0,
    moTa: 'Nạm bò hầm rượu vang quế hồi gấc đỏ sánh mịn',
  },
  {
    id: 44,
    ten: 'Gà kho gừng sả ớt',
    kcal: 270,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 26.0,
    bot: 5.0,
    beo: 16.0,
    moTa: 'Thịt gà ta chặt miếng kho gừng thơm nồng',
  },
  {
    id: 45,
    ten: 'Gà luộc lá chanh',
    kcal: 290,
    gram: 180,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 32.0,
    bot: 1.0,
    beo: 17.0,
    moTa: 'Thịt gà luộc da vàng chấm muối tiêu chanh',
  },
  {
    id: 46,
    ten: 'Vịt om sấu khoai sọ',
    kcal: 420,
    gram: 300,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 25.0,
    bot: 22.0,
    beo: 25.0,
    moTa: 'Thịt vịt béo om sấu chua thanh, khoai sọ bùi',
  },
  {
    id: 47,
    ten: 'Cá kho tộ ba chỉ',
    kcal: 290,
    gram: 150,
    donVi: 'khúc',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 24.0,
    bot: 7.0,
    beo: 18.0,
    moTa: 'Cá lóc/cá bống kho tiêu ớt nước màu dừa',
  },
  {
    id: 48,
    ten: 'Cá điêu hồng chiên xù mắm xoài',
    kcal: 340,
    gram: 200,
    donVi: 'phần',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 28.0,
    bot: 8.0,
    beo: 21.0,
    moTa: 'Cá điêu hồng chiên giòn chấm mắm tỏi ớt xoài băm',
  },
  {
    id: 49,
    ten: 'Cá thu sốt cà chua',
    kcal: 270,
    gram: 150,
    donVi: 'khúc',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 26.0,
    bot: 6.0,
    beo: 15.0,
    moTa: 'Cá thu rán sơ sốt cà chua thì là',
  },
  {
    id: 50,
    ten: 'Canh chua cá lóc',
    kcal: 160,
    gram: 350,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 18.0,
    bot: 12.0,
    beo: 4.5,
    moTa: 'Canh chua cá lóc bạc hà, giá, đậu bắp, dứa',
  },
  {
    id: 51,
    ten: 'Canh cua rau đay mướp',
    kcal: 95,
    gram: 350,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 8.0,
    bot: 10.0,
    beo: 2.2,
    moTa: 'Canh riêu cua đồng rau đay, mùng tơi, mướp hương',
  },
  {
    id: 52,
    ten: 'Canh sườn hầm rau củ',
    kcal: 240,
    gram: 350,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 16.0,
    bot: 20.0,
    beo: 10.0,
    moTa: 'Sườn heo hầm khoai tây, cà rốt ngọt tự nhiên',
  },
  {
    id: 53,
    ten: 'Canh bắp cải cuộn thịt bằm',
    kcal: 145,
    gram: 300,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 14.0,
    bot: 8.0,
    beo: 6.5,
    moTa: 'Bắp cải cuộn thịt heo nạc băm thắt cọng hành',
  },
  {
    id: 54,
    ten: 'Canh khổ qua nhồi thịt',
    kcal: 165,
    gram: 300,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 15.0,
    bot: 9.0,
    beo: 7.5,
    moTa: '1 trái mướp đắng nhồi thịt nạc băm nấm mèo',
  },
  {
    id: 55,
    ten: 'Canh ngao nấu chua dứa cà chua',
    kcal: 110,
    gram: 350,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 11.0,
    bot: 12.0,
    beo: 1.8,
    moTa: 'Canh ngao ngọt thanh nấu chua dứa, thì là',
  },
  {
    id: 56,
    ten: 'Canh rau ngót nấu thịt nạc',
    kcal: 120,
    gram: 300,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 13.0,
    bot: 7.0,
    beo: 4.5,
    moTa: 'Rau ngót tươi vò nát nấu thịt heo nạc',
  },
  {
    id: 57,
    ten: 'Đậu phụ nhồi thịt sốt cà',
    kcal: 260,
    gram: 200,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 19.0,
    bot: 10.0,
    beo: 15.0,
    moTa: '2 miếng đậu mơ nhồi thịt băm rim cà chua',
  },
  {
    id: 58,
    ten: 'Đậu phụ tẩm hành chiên',
    kcal: 210,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 12.0,
    bot: 6.0,
    beo: 15.0,
    moTa: 'Đậu phụ chiên nhúng mắm hành hoa nóng hổi',
  },
  {
    id: 59,
    ten: 'Trứng chiên thịt bằm hành',
    kcal: 270,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 18.0,
    bot: 3.0,
    beo: 20.0,
    moTa: '2 quả trứng gà đánh cùng thịt nạc xay chiên vàng',
  },
  {
    id: 60,
    ten: 'Rau muống xào tỏi',
    kcal: 135,
    gram: 180,
    donVi: 'đĩa',
    nhom: 'rau_qua',
    phanLoai: 'mon_viet',
    dam: 4.5,
    bot: 9.0,
    beo: 9.0,
    moTa: 'Rau muống non xanh giòn xào tỏi thơm',
  },
  {
    id: 61,
    ten: 'Su su xào thịt bò',
    kcal: 195,
    gram: 200,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'mon_viet',
    dam: 18.0,
    bot: 10.0,
    beo: 9.0,
    moTa: 'Su su bào sợi giòn ngọt xào thịt thăn bò',
  },
  {
    id: 62,
    ten: 'Cháo sườn quẩy giòn',
    kcal: 360,
    gram: 400,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'mon_viet',
    dam: 15.0,
    bot: 52.0,
    beo: 10.0,
    moTa: 'Cháo sườn xay mịn kèm ruốc và quẩy giòn',
  },

  // ==========================================
  // PHẦN 2: MÓN HEALTHY & GYMMER HAY ĂN (~43 món)
  // ==========================================
  {
    id: 63,
    ten: 'Ức gà áp chảo tiêu đen',
    kcal: 195,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 38.0,
    bot: 1.5,
    beo: 4.0,
    moTa: '150g ức gà fillet nạc áp chảo không dầu mỡ',
  },
  {
    id: 64,
    ten: 'Ức gà luộc xé phay',
    kcal: 175,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 39.0,
    bot: 0.0,
    beo: 2.2,
    moTa: '150g ức gà luộc chín tới mọng nước',
  },
  {
    id: 65,
    ten: 'Ức gà nướng sốt mù tạt mật ong',
    kcal: 210,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 37.0,
    bot: 5.0,
    beo: 4.5,
    moTa: 'Ức gà nướng nồi chiên không dầu sốt mustard',
  },
  {
    id: 66,
    ten: 'Thăn bò áp chảo dầu oliu',
    kcal: 255,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 36.0,
    bot: 0.5,
    beo: 11.5,
    moTa: 'Thăn bò mềm giàu sắt và creatine tự nhiên',
  },
  {
    id: 67,
    ten: 'Bắp bò luộc gừng sả',
    kcal: 215,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 35.0,
    bot: 1.0,
    beo: 7.5,
    moTa: 'Bắp bò hoa luộc giòn sần sật, ít mỡ',
  },
  {
    id: 68,
    ten: 'Thịt bò nạc băm xào ớt chuông',
    kcal: 230,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 31.0,
    bot: 6.0,
    beo: 9.0,
    moTa: 'Bò nạc xay xào ớt chuông giàu Vitamin C',
  },
  {
    id: 69,
    ten: 'Cá hồi áp chảo sốt chanh leo',
    kcal: 295,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 32.0,
    bot: 3.5,
    beo: 17.0,
    moTa: 'Cá hồi tươi giàu Omega-3 tốt cho tim và khớp',
  },
  {
    id: 70,
    ten: 'Cá hồi nướng măng tây',
    kcal: 280,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 31.0,
    bot: 2.0,
    beo: 16.0,
    moTa: 'Cá hồi nướng ăn kèm măng tây thanh mát',
  },
  {
    id: 71,
    ten: 'Cá ngừ hộp ngâm nước muối',
    kcal: 140,
    gram: 140,
    donVi: 'hộp',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 31.0,
    bot: 0.0,
    beo: 1.5,
    moTa: '1 hộp cá ngừ ngâm khoáng (Tuna in springwater)',
  },
  {
    id: 72,
    ten: 'Cá basa fillet áp chảo',
    kcal: 165,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 27.0,
    bot: 0.0,
    beo: 6.0,
    moTa: 'Fillet cá basa trắng mềm áp chảo tiêu',
  },
  {
    id: 73,
    ten: 'Tôm sú hấp sả chanh',
    kcal: 145,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 32.0,
    bot: 1.2,
    beo: 1.5,
    moTa: '150g thịt tôm hấp chín, đạm cao không béo',
  },
  {
    id: 74,
    ten: 'Trứng gà luộc lòng đào',
    kcal: 155,
    gram: 110,
    donVi: 'phần',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 13.0,
    bot: 1.1,
    beo: 10.5,
    moTa: '2 quả trứng gà luộc lòng đào chuẩn vị',
  },
  {
    id: 75,
    ten: 'Lòng trắng trứng chiên hành tây',
    kcal: 70,
    gram: 130,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 14.5,
    bot: 1.5,
    beo: 0.3,
    moTa: '4 lòng trắng trứng chiên thơm, đạm tinh khiết',
  },
  {
    id: 76,
    ten: 'Trứng ốp la dầu oliu',
    kcal: 185,
    gram: 110,
    donVi: 'đĩa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 13.0,
    bot: 1.2,
    beo: 14.0,
    moTa: '2 quả trứng ốp la dùng ít dầu oliu nguyên chất',
  },
  {
    id: 77,
    ten: 'Đậu phụ luộc chấm xì dầu',
    kcal: 120,
    gram: 150,
    donVi: 'bìa',
    nhom: 'thit_dam',
    phanLoai: 'gym_healthy',
    dam: 13.5,
    bot: 3.5,
    beo: 6.5,
    moTa: '1 bìa đậu hũ non luộc nóng, thanh đạm',
  },
  {
    id: 78,
    ten: 'Đậu nành non Edamame hấp',
    kcal: 122,
    gram: 100,
    donVi: 'chén',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 11.5,
    bot: 9.5,
    beo: 5.2,
    moTa: 'Đậu nành nguyên vỏ hấp rắc tí muối biển',
  },
  {
    id: 79,
    ten: 'Cơm gạo lứt huyết rồng',
    kcal: 165,
    gram: 150,
    donVi: 'chén',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 3.8,
    bot: 35.0,
    beo: 1.2,
    moTa: '1 chén gạo lứt đỏ giàu chất xơ, no lâu',
  },
  {
    id: 80,
    ten: 'Khoai lang luộc / hấp',
    kcal: 130,
    gram: 150,
    donVi: 'củ',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 2.4,
    bot: 30.0,
    beo: 0.2,
    moTa: '1 củ khoai lang vàng luộc mềm ~150g',
  },
  {
    id: 81,
    ten: 'Khoai lang mật nướng',
    kcal: 145,
    gram: 150,
    donVi: 'củ',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 2.2,
    bot: 33.0,
    beo: 0.3,
    moTa: 'Khoai lang mật nướng dẻo thơm',
  },
  {
    id: 82,
    ten: 'Yến mạch cán dẹt nấu chín',
    kcal: 190,
    gram: 120,
    donVi: 'bát',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 7.0,
    bot: 34.0,
    beo: 3.5,
    moTa: 'Yến mạch nguyên hạt nấu nước/sữa ấm',
  },
  {
    id: 83,
    ten: 'Overnight Oats yến mạch hạt chia',
    kcal: 280,
    gram: 200,
    donVi: 'hũ',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 14.0,
    bot: 42.0,
    beo: 6.5,
    moTa: 'Yến mạch ngâm sữa chua, hạt chia qua đêm',
  },
  {
    id: 84,
    ten: 'Hạt Quinoa (diêm mạch) nấu chín',
    kcal: 180,
    gram: 150,
    donVi: 'chén',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 6.5,
    bot: 32.0,
    beo: 3.0,
    moTa: 'Siêu thực phẩm Quinoa đủ 9 axit amin thiết yếu',
  },
  {
    id: 85,
    ten: 'Bánh mì đen nguyên cám',
    kcal: 165,
    gram: 70,
    donVi: 'phần',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 6.5,
    bot: 31.0,
    beo: 2.2,
    moTa: '2 lát bánh mì lúa mạch đen nguyên cám (Rye)',
  },
  {
    id: 86,
    ten: 'Bắp ngô ngọt luộc',
    kcal: 145,
    gram: 150,
    donVi: 'trái',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 4.5,
    bot: 31.0,
    beo: 1.8,
    moTa: '1 trái bắp ngô Mỹ luộc ngọt tự nhiên',
  },
  {
    id: 87,
    ten: 'Bông cải xanh (súp lơ) luộc',
    kcal: 50,
    gram: 150,
    donVi: 'đĩa',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 4.2,
    bot: 9.0,
    beo: 0.6,
    moTa: '150g súp lơ xanh hấp giòn giàu canxi & xơ',
  },
  {
    id: 88,
    ten: 'Măng tây xào dầu oliu tỏi',
    kcal: 65,
    gram: 120,
    donVi: 'đĩa',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 3.2,
    bot: 5.5,
    beo: 3.5,
    moTa: 'Măng tây tươi giòn xào nhẹ với tỏi đập dập',
  },
  {
    id: 89,
    ten: 'Đậu lăng hầm rau củ',
    kcal: 175,
    gram: 150,
    donVi: 'bát',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 12.0,
    bot: 28.0,
    beo: 1.5,
    moTa: 'Đậu lăng đỏ/xanh giàu đạm thực vật',
  },
  {
    id: 90,
    ten: 'Đậu gà luộc chín',
    kcal: 164,
    gram: 100,
    donVi: 'chén',
    nhom: 'tinh_bot',
    phanLoai: 'gym_healthy',
    dam: 8.9,
    bot: 27.0,
    beo: 2.6,
    moTa: 'Hạt đậu gà bùi béo, GI thấp',
  },
  {
    id: 91,
    ten: 'Salad ức gà xé sốt mè rang',
    kcal: 240,
    gram: 250,
    donVi: 'đĩa',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 28.0,
    bot: 11.0,
    beo: 9.0,
    moTa: 'Xà lách, cà chua bi, dưa leo, ức gà sốt mè',
  },
  {
    id: 92,
    ten: 'Salad cá ngừ bơ tươi dưa leo',
    kcal: 270,
    gram: 250,
    donVi: 'đĩa',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 25.0,
    bot: 10.0,
    beo: 14.0,
    moTa: 'Cá ngừ, bơ sáp cắt hạt lựu, sốt chanh sữa chua',
  },
  {
    id: 93,
    ten: 'Salad thăn bò rau mầm',
    kcal: 280,
    gram: 250,
    donVi: 'đĩa',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 27.0,
    bot: 8.0,
    beo: 15.0,
    moTa: 'Thăn bò tái áp chảo trộn rau mầm sốt dầu giấm',
  },
  {
    id: 94,
    ten: 'Canh rong biển đậu hũ non',
    kcal: 85,
    gram: 300,
    donVi: 'tô',
    nhom: 'mon_nuoc',
    phanLoai: 'gym_healthy',
    dam: 7.5,
    bot: 6.0,
    beo: 3.0,
    moTa: 'Rong biển thanh mát hầm thịt nạc đậu hũ non',
  },
  {
    id: 95,
    ten: 'Whey Protein Isolate pha nước',
    kcal: 120,
    gram: 30,
    donVi: 'muỗng',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 26.0,
    bot: 1.5,
    beo: 0.8,
    moTa: '1 muỗng Whey Isolate hấp thụ nhanh sau tập',
  },
  {
    id: 96,
    ten: 'Sinh tố Whey chuối bơ đậu phộng',
    kcal: 340,
    gram: 350,
    donVi: 'ly',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 32.0,
    bot: 35.0,
    beo: 8.0,
    moTa: 'Whey + 1 quả chuối tiêu + 1 thìa peanut butter',
  },
  {
    id: 97,
    ten: 'Sữa chua Hy Lạp không đường',
    kcal: 145,
    gram: 150,
    donVi: 'hũ',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 15.0,
    bot: 5.5,
    beo: 7.5,
    moTa: 'Sữa chua Hy Lạp sánh đặc gấp đôi lượng đạm',
  },
  {
    id: 98,
    ten: 'Sữa hạnh nhân không đường',
    kcal: 35,
    gram: 200,
    donVi: 'ly',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 1.2,
    bot: 1.5,
    beo: 2.8,
    moTa: '1 ly 200ml sữa hạt nguyên chất rất ít calo',
  },
  {
    id: 99,
    ten: 'Bơ đậu phộng nguyên chất',
    kcal: 125,
    gram: 20,
    donVi: 'muỗng',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 5.5,
    bot: 4.0,
    beo: 10.5,
    moTa: '1 muỗng canh 20g 100% đậu phộng rang xay mịn',
  },
  {
    id: 100,
    ten: 'Hạt hạnh nhân sấy mộc',
    kcal: 175,
    gram: 30,
    donVi: 'g',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 6.2,
    bot: 6.0,
    beo: 15.0,
    moTa: '1 nắm tay ~30g hạt hạnh nhân sấy không muối',
  },
  {
    id: 101,
    ten: 'Hạt óc chó sấy mộc',
    kcal: 195,
    gram: 30,
    donVi: 'g',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 4.5,
    bot: 4.0,
    beo: 19.0,
    moTa: '1 nắm hạt óc chó giàu DHA và chất béo tốt',
  },
  {
    id: 102,
    ten: 'Hạt chia ngâm nước ấm',
    kcal: 72,
    gram: 15,
    donVi: 'muỗng',
    nhom: 'do_uong',
    phanLoai: 'gym_healthy',
    dam: 2.5,
    bot: 6.0,
    beo: 4.5,
    moTa: '1 muỗng canh hạt chia ngâm nở giúp no lâu',
  },
  {
    id: 103,
    ten: 'Quả bơ sáp cắt lát',
    kcal: 160,
    gram: 100,
    donVi: 'g',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 2.0,
    bot: 8.5,
    beo: 14.5,
    moTa: '100g bơ Đắk Lắk dẻo béo, chất béo đơn không no',
  },
  {
    id: 104,
    ten: 'Chuối tiêu chín tự nhiên',
    kcal: 89,
    gram: 100,
    donVi: 'trái',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 1.1,
    bot: 23.0,
    beo: 0.3,
    moTa: '1 quả chuối vừa bổ sung kali và năng lượng tập',
  },
  {
    id: 105,
    ten: 'Táo Envy tươi giòn',
    kcal: 80,
    gram: 150,
    donVi: 'trái',
    nhom: 'rau_qua',
    phanLoai: 'gym_healthy',
    dam: 0.4,
    bot: 21.0,
    beo: 0.3,
    moTa: '1 quả táo tươi nhiều pectin và chất chống oxy hóa',
  },
];

/**
 * Công thức tính lại macro và calo theo tỷ lệ khối lượng tiêu thụ
 */
export function tinhMacroTheoKhoiLuong(
  luongMoiGram: number,
  chuan: {
    baseGram: number;
    baseKcal: number;
    baseDam?: number | null;
    baseBot?: number | null;
    baseBeo?: number | null;
  }
): { kcal: number; dam: number; bot: number; beo: number } {
  const gChuan = chuan.baseGram > 0 ? chuan.baseGram : 100;
  const tiLe = luongMoiGram / gChuan;

  const kcal = Math.max(0, Math.round(chuan.baseKcal * tiLe));
  const dam = Math.max(0, Math.round(((chuan.baseDam ?? 0) * tiLe) * 10) / 10);
  const bot = Math.max(0, Math.round(((chuan.baseBot ?? 0) * tiLe) * 10) / 10);
  const beo = Math.max(0, Math.round(((chuan.baseBeo ?? 0) * tiLe) * 10) / 10);

  return { kcal, dam, bot, beo };
}
